### ISSUE TITLE
Remove shx from dependencies and add to devDependencies instead

### ISSUE THREAD

**Issue by restfulhead** [LottieFiles/lottie-player#139] opened 2022-01-31 21:37 UTC
As far as I can see, `shx` is used to build the library. It should not be part of `dependencies`. This causes `shx` to become a dependency of people who use the library.

**Comment by samuelOsborne** [comment] 2022-02-01 08:35
Closing due to being a duplicate of #132

**Closed by samuelOsborne** 2022-02-01 08:35 UTC
