### ISSUE TITLE
Google Lighthouse – [aria-*] attributes do not match their roles

### ISSUE THREAD

**Issue by dentsuAchtung** [LottieFiles/lottie-player#116] opened 2021-11-09 14:08 UTC
Hello,

I'm using multiple lottie players on the same webpage, and everything is working as expected (thank you for that).
But as soon as I run Google Lighthouse, I'm getting the following error under "Accessibility": 

**[aria-*] attributes do not match their roles**
_Each ARIA `role` supports a specific subset of `aria-*` attributes. Mismatching these invalidates the `aria-*` attributes._

I've set up the lottie file as follows:

`<lottie-player id='lottie-in-animation'
                                    ref={refLottieIn}
                                    mode='normal'
                                    controls={false}
                                    loop={false}
                                    description='Propeller circle'
                                    src={"/PATH_TO_JSON.json"}
                                    style={{ width: "100%", height: "100%" }}></lottie-player>`

This renders all fine and creates a lottie player component with a shadow root that you can inspect in the devtools.
That brings us to the `aria-label` issue that Google Lighthouse points out. I found out that this library supports the `description` attribute and creates an aria label of that property. If the `description` attribute is not filled in, it falls back to the text "Lottie animation". 

In my opinion, there is no need to add an `aria-label` to the `<lottie-player>` element, so my question is if that maybe can be disabled?

Thank you in advance and for all the work on this library – it's great.

**Comment by karamalie** [comment] 2021-11-18 06:04
The aria labels were added as part of an accessibility effort. For users who browse the web without sight, the description acts as a voiceover feature. Ideally would like to keep it in but will make an effort to ensure that the lighthouse error is fixed though

**Comment by samuelOsborne** [comment] 2021-11-30 11:21
Hi @dentsuAchtung, I've not managed to reproduce your problem as when I test out Lighthouse on a page with a single I get the following results where there are no aria related problems:

![image](https://user-images.githubusercontent.com/23125742/144037635-49ca566d-c533-4b08-b74c-e3da0a0d79cd.png)

Are you using the latest version of the lottie-player? And are you sure its related to the lottie-player? If possible a codepen reproducing this issue would be a great help.

**Comment by samuelOsborne** [comment] 2021-12-16 13:00
Hey @dentsuAchtung, are you still having this problem with the latest version of the player?

**Comment by Nathan-deGraaf** [comment] 2021-12-16 21:28
Hi Guys, I recently reached out to the surpport staff, and this issue has been resolved. you can see the issue of an incorrect role being addressed in this following [https://github.com/LottieFiles/lottie-player/releases/tag/v1.3.0 ]link

**Comment by samuelOsborne** [comment] 2021-12-17 08:21
Cheers @Nathan-deGraaf, closing this issue.

**Closed by samuelOsborne** 2021-12-17 08:21 UTC

**Comment by joanvf** [comment] 2022-04-18 08:31
Hi everyone,

Hope all is well. We are facing this issue. Google Lighthouse is pointing out that aria- attributes in the Lottie animation do not match roles, reducing the overall website score.

<img width="466" alt="Screenshot 2022-04-14 at 14 45 49" src="https://user-images.githubusercontent.com/53238150/163780265-40303f77-d3d9-420b-a264-c567e8738dca.png">

Check the animation here [here](https://singularly.com) 

How did you solve it last time?

Many thanks

**Comment by samuelOsborne** [comment] 2022-04-22 12:02
@joanvf When I look at your frontpage I don't see any errors due to aria-labels?
![image](https://user-images.githubusercontent.com/23125742/164710558-fac3ad24-b33e-470b-a29c-c2deead2a113.png)

**Comment by joanvf** [comment] 2022-04-23 14:30
That is very strange, it was giving errors a week ago and we didn't make any change/upgrade neither to the player nor to the animation. May have been due to Chrome's version...? In any case, thanks so much @samuelOsborne for helping! Really appreciated!

**Comment by zheeeng** [comment] 2022-07-29 16:58
I encountered this problem when trying to raise my website score. Google Lighthouse reports the `aria-label` attribute mismatches the element's role.

According to specifications, Lighthouse points to this element:
`<g aria-label="some text"></g>`
