### ISSUE TITLE
Local Assets wont display

### ISSUE THREAD

**Issue by SilasNiewierra** [LottieFiles/lottie-player#114] opened 2021-11-05 12:28 UTC
Hi there,

I really love this package. But I'm running into a problem. I want to display a lottie-file which I downloaded (.json).
This file is in my /public/animations folder.
I tried to implemented it like this:

```js
<lottie-player
        src="@/public/animations/lf30_editor_t2jod6gq.json"
        background="transparent"
        speed="0.5"
        class="lottie-player"
        loop
        autoplay
      />
```

but this doesn't work. However if I use a random lottie-file url from the community, everything works fine 🤔 
Does the library allow local .json files as input?

**Comment by karamalie** [comment] 2021-11-08 06:27
It should by right allow local files too yes. will run some tests and get back to you @SilasNiewierra

**Comment by SilasNiewierra** [comment] 2021-11-08 06:45
That would be amazing, thanks a lot @karamalie . Still struggling with that problem 🤔

**Comment by SilasNiewierra** [comment] 2021-11-08 07:07
In more detail, I get the following error:
```
 DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').
    at t (https://unpkg.com/@lottiefiles/lottie-player@0.4.0/dist/lottie-player.js:38:66874)
```

**Comment by karamalie** [comment] 2021-11-08 07:41
@SilasNiewierra https://codesandbox.io/s/nifty-jennings-8g8xo?file=/index.html built a small demo. it definitely does take in the local json file. but im using the latest version of the player. could it be the path reference on your side?

**Comment by SilasNiewierra** [comment] 2021-11-08 07:59
Hey @karamalie I checked out your demo, but you're not using your phone.js or am I missing something?
You're still using : src="https://assets9.lottiefiles.com/datafiles/gUENLc1262ccKIO/data.json" as your src?

**Comment by karamalie** [comment] 2021-11-08 08:00
<img width="492" alt="Screenshot 2021-11-08 at 3 59 48 PM" src="https://user-images.githubusercontent.com/12868819/140704689-70e5a582-9301-4b85-bf7f-aab340d4e02e.png">

**Comment by karamalie** [comment] 2021-11-08 08:02
wonder if the example didnt update. https://codesandbox.io/s/nifty-jennings-8g8xo?file=/index.html try again with this?

**Comment by SilasNiewierra** [comment] 2021-11-08 08:16
Okay it seems to work in your CodeSandbox, which is cool.
I still have the problem when using it in Vue?
```js
<template>
  <transition
    name="move-up"
    class="player-container"
  >
    <div
      v-if="showAnimation"
      class="justify-center player-container d-flex"
    >
      <lottie-player
        src="../../public/animations/rocket.json"
        background="transparent"
        speed="0.5"
        style="width: 300px; height: 300px;"
        loop
        autoplay
      />
    </div>
  </transition>
</template>

<script>
import bus from '@/lib/eventBus'

export default {
  data () {
    return {
      showAnimation: false,
      imageSrc: ''
    }
  },

  async mounted () {
    bus.$on('show-animation', () => {
      this.showAnimation = true
      setTimeout(() => {
        this.showAnimation = false
      }, 1900)
    })
  }

}
</script>

<style scoped>
.player-container{
  position: absolute;
  top: 0;
  height: 100%;
  width: 100%;
  z-index: 1000;
  opacity: 0;
  background-color: red;
}

.move-up-enter-active {
    animation: move-up 2s;
}

@keyframes move-up {
    0% { opacity: 0; transform: translateY(1000px);  }
    70% { opacity: 1; transform: translateY(300px); }
    99% { opacity: 1; transform: translateY(-300px);  }
    100% { opacity: 0; transform: translateY(-300px);  }
}

</style>

```

Doing this results in the following error: 
```
Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').
```

**Comment by SilasNiewierra** [comment] 2021-11-08 08:16
Can you please try to make a working CodeSandbox with Vue?

**Comment by SilasNiewierra** [comment] 2021-11-08 11:13
I was able to get it running by using lottie-web directly.

**Comment by karamalie** [comment] 2021-11-09 08:09
might have to do with how the player is loaded on vue too. in vuejs the lottie-player has to be loaded up as a client side only script. otherwise it will fail. This is by design as we wrapped the lottie-web as a web component for performance boost

**Comment by karamalie** [comment] 2021-11-09 08:20
managed to replicate the same issue @SilasNiewierra . in vuejs the player isnt resolving the correct url when the path is relative. you can serve the json file from your public folder and still play it though (alternative). will have a look into what kind of fix can be implemented to resolve the relative paths. however if the lottie-web works for you then you may continue using it.

**Comment by MayheMatan** [comment] 2021-12-13 08:13
any updates regarding that issue?

**Comment by samuelOsborne** [comment] 2021-12-13 10:21
Hi @MayheMatan is your issue with the lottie-player (this repo) or the vue wrapper we have? This conversation turned to the vue wrapper but your issue might be with the player. Will be checking this out this week, let me know, cheers!

**Comment by MayheMatan** [comment] 2021-12-13 10:59
My issue is with vue, i cannot pass relative pathes in the stc attribute.

**Comment by samuelOsborne** [comment] 2021-12-13 11:09
@MayheMatan Can you share the error please? I can load local animations from the public folder:

```
      <lottie-vue-player :src="`./frosted-glass.json`"
                         :theme="options.theme"
                         :player-size="options.playerSize"
                         :player-controls="true"
                         :show-color-picker="true"
                         style="width: 100%; height:400px"></lottie-vue-player>
```

**Comment by MayheMatan** [comment] 2021-12-13 12:21
using nuxt framework:
`
            <lottie-player
                :src="`../../../chat/src/assets/chat-loader.json`"
                class="loader"
                loop
                autoplay
            />

`

actually adding my domain to the src and then the src on the web inspector looks like:
https://{myDomainHere}/chat/src/assets/chat-loader.json

**Comment by samuelOsborne** [comment] 2021-12-15 10:17
@MayheMatan does that method load up the assets correctly?

**Comment by MayheMatan** [comment] 2021-12-15 11:22
no

**Comment by samuelOsborne** [comment] 2021-12-15 13:24
@MayheMatan Using Nuxt and storing your animations in the 'static' directory will prevent them from being bundled with webpack and allow you to serve them. My working setup was as is:

```
project
│
└─── assets
│   │   style.scss
│   
└─── static
    │   animation.json
```

And then in my .vue file:

```javascript
    <lottie-player
      autoplay
      controls
      loop
      style="width:400px"
      src="/animation.json"
      speed="1"
      debug
    ></lottie-player>
```

**Closed** 2021-12-16 13:02 UTC
